batch_size: 12
config_type: correlation
cutout: false
cutout_length: 16
cutout_prob: 0
dataset: class_object
out_dir: run
predictor: linear_region
search_space: transbench101_macro
seed: 9000
test_size: 1000
train_portion: 0.7
