batch_size: 32
config_type: correlation
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: scifar100
out_dir: run
predictor: jacov
search_space: nasbench301
seed: 9008
test_size: 1000
train_portion: 0.7
