batch_size: 32
config_type: correlation
cutout: false
cutout_length: 16
cutout_prob: 0
dataset: cifar10
out_dir: run
predictor: linear_region
search_space: nasbench201
seed: 9000
test_size: 1000
train_portion: 0.7
