batch_size: 32
config_type: correlation
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: room_layout
out_dir: run
predictor: jacov
search_space: transbench101_macro
seed: 9004
test_size: 1000
train_portion: 0.7
